const data = [
  {
    eng: "Potato",
    img: "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg",
    japanese: { lang: "じゃがいも", slug: "Jagaimo" },
    hindi: { lang: "आलू", slug: "aaloo" },
  },
  {
    eng: "Tomato",
    img: "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg",
    japanese: { lang: "トマト", slug: "Tomato" },
    hindi: { lang: "टमाटर", slug: "tamaatar" },
  },
  {
    eng: "Carrot",
    img: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    japanese: { lang: "にんじん", slug: "Ninjin" },
    hindi: { lang: "गाजर", slug: "gaajar" },
  },
  {
    eng: "Onion",
    img: "https://wallpaperaccess.com/full/1912934.jpg",
    japanese: { lang: "タマネギ", slug: "Tamanegi" },
    hindi: { lang: "प्याज", slug: "pyaaj" },
  },
  {
    eng: "Garlic",
    img: "https://www.goodwholefood.com/wp-content/uploads/2015/09/GarlicCloves.jpg",
    japanese: { lang: "ニンニク", slug: "Nin'niku" },
    hindi: { lang: "लहसुन", slug: "lahasun" },
  },
  {
    eng: "Cucumber",
    img: "https://images.pexels.com/photos/2329440/pexels-photo-2329440.jpeg",
    japanese: { lang: "キュウリ", slug: "Kyūri" },
    hindi: { lang: "खीरा", slug: "kheera" },
  },
  {
    eng: "Lettuce",
    img: "https://images.pexels.com/photos/1199562/pexels-photo-1199562.jpeg",
    japanese: { lang: "レタス", slug: "Retasu" },
    hindi: { lang: "सलाद", slug: "salaad" },
  },
  {
    eng: "Spinach",
    img: "https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg",
    japanese: { lang: "ほうれん草", slug: "Hōrensō" },
    hindi: { lang: "पालक", slug: "paalak" },
  },
  {
    eng: "Broccoli",
    img: "http://priorityseed.com/wp-content/uploads/2015/08/Broccoli.jpg",
    japanese: { lang: "ブロッコリー", slug: "Burokkorī" },
    hindi: { lang: "ब्रोकोली", slug: "brokolee" },
  },
  {
    eng: "Cauliflower",
    img: "https://images.pexels.com/photos/1227806/pexels-photo-1227806.jpeg",
    japanese: { lang: "カリフラワー", slug: "Karifurawā" },
    hindi: { lang: "फूलगोभी", slug: "phoolagobhee" },
  },
  {
    eng: "Peas",
    img: "https://images.pexels.com/photos/255469/pexels-photo-255469.jpeg",
    japanese: { lang: "豆", slug: "Mame" },
    hindi: { lang: "मटर", slug: "matar" },
  },
  {
    eng: "Green beans",
    img: "https://images.pexels.com/photos/3004798/pexels-photo-3004798.jpeg",
    japanese: { lang: "サヤインゲン", slug: "Sayaingen" },
    hindi: { lang: "हरी सेम", slug: "haree sem" },
  },
  {
    eng: "Capsicum",
    img: "https://images.pexels.com/photos/1374651/pexels-photo-1374651.jpeg",
    japanese: { lang: "トウガラシ属", slug: "Tōgarashi zoku" },
    hindi: {
      lang: "शिमला मिर्च",
      slug: "shimala mirch",
    },
  },
  {
    eng: "Brinjal",
    img: "https://i.pinimg.com/originals/02/c3/24/02c324a70e8f0193fc9d7e899b2af111.png",
    japanese: { lang: "ナス/ブリンジャル", slug: "Nasu/ burinjaru" },
    hindi: { lang: "बैंगन/ब्रिंजल", slug: "baingan/brinjal" },
  },
  {
    eng: "Zucchini",
    img: "https://images.pexels.com/photos/128420/pexels-photo-128420.jpeg",
    japanese: { lang: "ズッキーニ", slug: "Zukkīni" },
    hindi: { lang: "तुरई", slug: "turee" },
  },
  {
    eng: "Pumpkin",
    img: "http://www.oldfashionedfamilies.com/wp-content/uploads/2015/09/Pumpkin.jpg",
    japanese: { lang: "かぼちゃ", slug: "Kabocha" },
    hindi: { lang: "कद्दू", slug: "kaddoo" },
  },
  {
    eng: "Butternut Squash",
    img: "https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/284/284479/butternut-squash.jpg?w=1155&h=1642",
    japanese: {
      lang: "バターナットスカッシュ",
      slug: "Batānatto sukasshu",
    },
    hindi: { lang: "बटरनट स्क्वाश", slug: "bataranat skvaash" },
  },
  {
    eng: "Sweet potato",
    img: "https://leaf.nutrisystem.com/wp-content/uploads/2017/08/ThinkstockPhotos-497961226.jpg",
    japanese: { lang: "さつまいも", slug: "Satsumaimo" },
    hindi: { lang: "शकरकंद", slug: "shakarakand" },
  },
  {
    eng: "Beetroot",
    img: "https://images.hellomagazine.com/horizon/landscape/b8f950e8de20-beetroots-t.jpg",
    japanese: { lang: "ビートルート", slug: "Bītorūto" },
    hindi: { lang: "चुकंदर", slug: "chukandar" },
  },
  {
    eng: "Radish",
    img: "https://cdn.mos.cms.futurecdn.net/266BbfCxKKcyrp7gbiBfdf.jpg",
    japanese: { lang: "だいこん", slug: "Daikon" },
    hindi: { lang: "मूली", slug: "moolee" },
  },
  {
    eng: "Turnip",
    img: "https://i0.wp.com/cdn-prod.medicalnewstoday.com/content/images/articles/284/284815/a-bunch-of-turnips-on-a-table.jpg?w=1155&h=1734",
    japanese: { lang: "カブ", slug: "Kabu" },
    hindi: { lang: "शलजम", slug: "shalajam" },
  },
  {
    eng: "Celery",
    img: "https://specialtyproduce.com/sppics/13456.png",
    japanese: { lang: "セロリ", slug: "Serori" },
    hindi: { lang: "अजमोदा", slug: "ajamoda" },
  },
  {
    eng: "Cabbage",
    img: "https://static.horizontimes.com/wp-content/uploads/2019/07/23134636/Cabbage-20190723134635-20190723134635.jpg",
    japanese: { lang: "キャベツ", slug: "Kyabetsu" },
    hindi: { lang: "पत्ता गोभी", slug: "patta gobhee" },
  },
  {
    eng: "Brussels sprouts",
    img: "https://images.pexels.com/photos/41171/brussels-sprouts-sprouts-cabbage-grocery-41171.jpeg",
    japanese: { lang: "芽キャベツ", slug: "Mekyabetsu" },
    hindi: { lang: "ब्रसल स्प्राउट", slug: "brasal spraut" },
  },
  {
    eng: "Kale",
    img: "https://images.pexels.com/photos/51372/kale-vegetables-brassica-oleracea-var-sabellica-l-51372.jpeg",
    japanese: { lang: "ケール", slug: "Kēru" },
    hindi: { lang: "गोभी", slug: "gobhee" },
  },
  {
    eng: "Asparagus",
    img: "https://images.pexels.com/photos/351679/pexels-photo-351679.jpeg",
    japanese: { lang: "アスパラガス", slug: "Asuparagasu" },
    hindi: { lang: "एस्परैगस", slug: "esparaigas" },
  },
  {
    eng: "Artichoke",
    img: "https://images.pexels.com/photos/3912846/pexels-photo-3912846.jpeg",
    japanese: { lang: "アーティチョーク", slug: "Ātichōku" },
    hindi: { lang: "हाथी चक", slug: "haathee chak" },
  },
  {
    eng: "Mushroom",
    img: "https://www.healthbenefitstimes.com/glossary/wp-content/uploads/2020/09/Mushroom.jpg",
    japanese: { lang: "キノコ", slug: "Kinoko" },
    hindi: { lang: "मशरूम", slug: "masharoom" },
  },
  {
    eng: "Leek",
    img: "http://freefoodphotos.com/imagelibrary/vegetables/fresh_leeks.jpg",
    japanese: { lang: "リーキ", slug: "Rīki" },
    hindi: { lang: "हरा प्याज", slug: "hara pyaaj" },
  },
  {
    eng: "Okra/Lady Finger",
    img: "https://voices.shortpedia.com/wp-content/uploads/2021/07/lady-finger-1200x900-1.jpg",
    japanese: {
      lang: "オクラ / レディフィンガー",
      slug: "Okura/ redifingā",
    },
    hindi: { lang: "लेडी फिंगर", slug: "ledee phingar" },
  },
  {
    eng: "Corn",
    img: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg",
    japanese: { lang: "トウモロコシ", slug: "Tōmorokoshi" },
    hindi: { lang: "भुट्टा", slug: "bhutta" },
  },
  {
    eng: "Green onion",
    img: "http://www.dvo.com/newsletter/weekly/2015/1-9-115/w_images/onion_green.jpg",
    japanese: { lang: "緑ネギ", slug: "Midori negi" },
    hindi: { lang: "हरी प्याज", slug: "haree pyaaj" },
  },
  {
    eng: "Bok choy",
    img: "https://kj1bcdn.b-cdn.net/media/44677/bok-choy.jpg",
    japanese: { lang: "チンゲン菜", slug: "Chin gensai" },
    hindi: { lang: "बुक चॉय", slug: "buk choy" },
  },
  {
    eng: "Cilantro",
    img: "https://images.pexels.com/photos/1275204/pexels-photo-1275204.jpeg",
    japanese: { lang: "コリアンダー", slug: "Koriandā" },
    hindi: { lang: "धनिया", slug: "dhaniya" },
  },
  {
    eng: "Parsley",
    img: "https://images.pexels.com/photos/60639/parsley-seasoning-salad-greens-60639.jpeg",
    japanese: { lang: "パセリ", slug: "Paseri" },
    hindi: { lang: "अजमोद", slug: "ajamod" },
  },
  {
    eng: "Dill",
    img: "http://nashsorganicproduce.com/recipes/wp-content/uploads/2013/04/dill-2.jpg",
    japanese: { lang: "ディル", slug: "Diru" },
    hindi: { lang: "सोया", slug: "soya" },
  },
  {
    eng: "Ginger",
    img: "https://images.pexels.com/photos/1337585/pexels-photo-1337585.jpeg",
    japanese: { lang: "ショウガ", slug: "Shōga" },
    hindi: { lang: "अदरक", slug: "adarak" },
  },
  {
    eng: "Turmeric",
    img: "https://images.pexels.com/photos/1340116/pexels-photo-1340116.jpeg",
    japanese: { lang: "ターメリック", slug: "Tāmerikku" },
    hindi: { lang: "हल्दी", slug: "haldee" },
  },
  {
    eng: "Fenugreek",
    img: "https://cdn-prod.medicalnewstoday.com/content/images/hero/324/324334/324334_1100.jpg",
    japanese: { lang: "フェヌグリーク", slug: "Fenugurikku" },
    hindi: { lang: "मेंथी", slug: "menthee" },
  },
  {
    eng: "Mustard greens",
    img: "https://www.rawl.net/media/1131/mustard_1200.jpg",
    japanese: { lang: "マスタートガークン", slug: "Masutatugunku" },
    hindi: { lang: "सरसों का साग", slug: "sarason ka saag" },
  },
  {
    eng: "Swiss chard",
    img: "https://cdn.mos.cms.futurecdn.net/ysQRfYRnBnbZ4zUE64kQKi-1536-80.jpg",
    japanese: { lang: "スイスチャド", slug: "Suisutad" },
    hindi: { lang: "स्विस कार्ड", slug: "svis kaard" },
  },
  {
    eng: "Watercress",
    img: "https://cornvalefoods.co.uk/wp-content/uploads/2021/01/watercress-1152x922-1.jpg",
    japanese: { lang: "クレソン", slug: "Kureson" },
    hindi: { lang: "जलकुंभी", slug: "jalkubi" },
  },
  {
    eng: "Arugula",
    img: "https://static.fanpage.it/wp-content/uploads/sites/22/2018/02/arugula-2.jpg",
    japanese: { lang: "ルッコラ", slug: "Rukkora" },
    hindi: { lang: "आर्गुला", slug: "aargula" },
  },
  {
    eng: "Radicchio",
    img: "https://images.pexels.com/photos/2539419/pexels-photo-2539419.jpeg",
    japanese: { lang: "ラディッキオ", slug: "Radikkio" },
    hindi: { lang: "रेडिकिचियो", slug: "redikichiyo" },
  },
  {
    eng: "Endive",
    img: "https://morningchores.com/wp-content/uploads/2020/06/belgian-endive.jpg",
    japanese: { lang: "エンダイブ", slug: "endaibu" },
    hindi: { lang: "विलायती", slug: "vilaayatee" },
  },
  {
    eng: "Chicory",
    img: "https://cdn.mos.cms.futurecdn.net/7Pivc3mNF9ZKTujv9FP3XC-1536-80.jpg",
    japanese: { lang: "チコリ", slug: "Chikori" },
    hindi: { lang: "कासनी", slug: "kaasanee" },
  },
  {
    eng: "Fennel",
    img: "https://images.pexels.com/photos/159357/fennel-vegetables-fennel-bulb-food-159357.jpeg",
    japanese: { lang: "ウイキョウ", slug: "Uikyō" },
    hindi: { lang: "सौंफ", slug: "saumph" },
  },
  {
    eng: "Bamboo shoots",
    img: "https://harcourthealth.com/wp-content/uploads/2019/01/bamboo-shoots-nutrition.jpg",
    japanese: { lang: "たけのこ", slug: "takenoko" },
    hindi: { lang: "Baans karli", slug: "baans karli" },
  },
  {
    eng: "Wild Spinach",
    img: "https://specialtyproduce.com/sppics/4181.png",
    japanese: { lang: "野生のほうれん草", slug: "Yasei no hōrensō" },
    hindi: { lang: "बथुआ", slug: "bthuaa" },
  },
  {
    eng: "Kohlrabi",
    img: "https://www.thehealthjournals.com/wp-content/uploads/2014/02/kohlrabi-1.jpg",
    japanese: { lang: "コールラビ", slug: "Kōrurabi" },
    hindi: { lang: "कोल्हाबी", slug: "kolhaabee" },
  },
  {
    eng: "Elephant Foot Yam",
    img: "https://media.licdn.com/dms/image/C4D12AQE4OcJXpyg2NQ/article-cover_image-shrink_600_2000/0/1645788545429?e=2147483647&v=beta&t=KVmhigGJSFern3HYSycfD80H2Mls5QB1jTG-0Jx3vO4",
    japanese: { lang: "象の足ヤム", slug: "Zō no ashi yamu" },
    hindi: { lang: "जिमीकंद", slug: "jimikand" },
  },
  {
    eng: "Lemon grass",
    img: "https://healthyliving.natureloc.com/wp-content/uploads/2015/07/1.jpg",
    japanese: { lang: "レモングラス", slug: "Remongurasu" },
    hindi: { lang: "भूतकेशी", slug: "bhootakeshee" },
  },
  {
    eng: "Water chestnut",
    img: "https://chefsmandala.com/wp-content/uploads/2018/03/Water-Chestnut.jpg",
    japanese: { lang: "水栗", slug: "Mikuri" },
    hindi: { lang: "सिंघाड़ा", slug: "singhaada" },
  },
  {
    eng: "Lotus root",
    img: "https://misosoup.site/wp-content/uploads/2020/09/lotusroot.jpg",
    japanese: { lang: "レンコン", slug: "Renkon" },
    hindi: { lang: "कमल जड़", slug: "kamal jad" },
  },
  {
    eng: "Daikon radish",
    img: "https://images.pexels.com/photos/7214603/pexels-photo-7214603.jpeg",
    japanese: { lang: "だいこん", slug: "Daikon" },
    hindi: { lang: "मूली", slug: "moolee" },
  },
  {
    eng: "Winter melon",
    img: "https://emozzy.com/wp-content/uploads/2020/09/blue_dynamic_fitness_Vho0D-1536x864.jpg",
    japanese: {
      lang: "冬のメロン",
      slug: "Fuyu no meron",
    },
    hindi: {
      lang: "ऐश लौकी",
      slug: "aish laukee",
    },
  },
  {
    eng: "Taro root",
    img: "https://www.organicfacts.net/wp-content/uploads/taroroot.jpg",
    japanese: { lang: "TAROルート", slug: "Tarō rūto" },
    hindi: { lang: "तारो जड़", slug: "taaro jad" },
  },
  {
    eng: "Cassava",
    img: "https://images.pexels.com/photos/7543155/pexels-photo-7543155.jpeg",
    japanese: { lang: "キャッサバ", slug: "Kyassaba" },
    hindi: { lang: "कसावा", slug: "kasaava" },
  },
  {
    eng: "Bitter melon",
    img: "https://healthjade.com/wp-content/uploads/2017/11/bitter-melon.jpg",
    japanese: { lang: "ゴーヤ", slug: "Gōya" },
    hindi: { lang: "कड़वा तरबूज", slug: "kadava tarabooj" },
  },
  {
    eng: "Winged bean",
    img: "https://i.etsystatic.com/27336320/r/il/b5a80f/2957438901/il_1588xN.2957438901_f13t.jpg",
    japanese: { lang: "翼のある豆", slug: "Tsubasa no aru mame" },
    hindi: { lang: "विंगड बीन", slug: "vingad biin" },
  },
  {
    eng: "Chayote",
    img: "https://frutasyverduras.info/wp-content/uploads/2019/07/chayote-propiedades.jpg",
    japanese: { lang: "押しつぶす", slug: "Oshitsubusu" },
    hindi: { lang: "इस्कुस", slug: "iskus" },
  },
  {
    eng: "Snake gourd",
    img: "https://www.organicfacts.net/wp-content/uploads/snakegourdtwo.jpg",
    japanese: { lang: "ヘビのひょうたん", slug: "Hebi no hyōtan" },
    hindi: { lang: "चिचिण्डा", slug: "chichinda" },
  },
  {
    eng: "Bottle gourd",
    img: "https://images.pexels.com/photos/6397648/pexels-photo-6397648.jpeg",
    japanese: { lang: "ヒョウタン", slug: "Hyōtan" },
    hindi: { lang: "लौकी", slug: "laukee" },
  },
  {
    eng: "Ridged gourd",
    img: "https://www.nutritionfact.in/wp-content/uploads/2020/03/ridgegourad.jpg",
    japanese: { lang: "隆起したひょうたん", slug: "Ryūki shita hyōtan" },
    hindi: { lang: "चकित", slug: "chakit" },
  },
  {
    eng: "Ivy gourd",
    img: "https://jooinn.com/images/ivy-gourd.jpg",
    japanese: { lang: "アイビーのひょうたん", slug: "Aibī no hyōtan" },
    hindi: { lang: "आइवी लौकी", slug: "aaivee laukee" },
  },
  {
    eng: "Curry leaves",
    img: "https://www.bombayspices.ca/wp-content/uploads/2019/03/CURRY-LEAVES.jpg",
    japanese: { lang: "カレーの葉", slug: "Karē no ha" },
    hindi: { lang: "करी पत्ते", slug: "karee patte" },
  },
  {
    eng: "Pointed gourd",
    img: "https://homesteadgardener.com/wp-content/uploads/2023/07/growing-pointed-gourd-1024x683.jpg",
    japanese: { lang: "尖ったひょうたん", slug: "Togatta hyōtan" },
    hindi: { lang: "नुकीला लौकी", slug: "nukeela laukee" },
  },
  {
    eng: "Drumstick",
    img: "https://prod-admin-images.s3.ap-south-1.amazonaws.com/7x2Ps1g9Ho9XCt2IpV1E-1/product/00352-Drumstick16.jpg",
    japanese: { lang: "ドラムスティック", slug: "Doramusutikku" },
    hindi: { lang: "ढोल का छड़ी", slug: "dhol ka chhadee" },
  },
  {
    eng: "Jackfruit",
    img: "https://images.pexels.com/photos/19229289/pexels-photo-19229289.jpeg",
    japanese: { lang: "ジャックフルーツ", slug: "Jakkufurūtsu" },
    hindi: { lang: "खलनाश", slug: "khalanaash" },
  },
  {
    eng: "Apple gourd",
    img: "https://cdn.shopify.com/s/files/1/1904/8475/products/Gourd_-_Apple_Gourd_1024x1024.jpg?",
    japanese: { lang: "Apple Gourd", slug: "Appuru Gourd" },
    hindi: { lang: "सेब की गड़गड़ाहट", slug: "seb kee gadagadaahat" },
  },
  {
    eng: "White Goosefoot",
    img: "https://ecorganicas.com/wp-content/uploads/2022/08/nature-3246581_1920.jpg",
    japanese: { lang: "ホワイトグースフット", slug: "Howaitogūsufutto" },
    hindi: { lang: "सफेद गोसेफुट", slug: "saphed gosephut" },
  },
  {
    eng: "Red Chilli",
    img: "https://images.pexels.com/photos/39390/chili-pepper-red-spicy-drying-39390.jpeg",
    japanese: { lang: "赤い唐辛子", slug: "Akai tōgarashi" },
    hindi: { lang: "लाल मिर्च", slug: "laal mirch" },
  },
  {
    eng: "Green Chilli",
    img: "https://www.hopscotch.in/blog/wp-content/uploads/2020/02/Greenchillies.FI-1.jpg",
    japanese: { lang: "青唐辛子", slug: "Ao tōgarashi" },
    hindi: { lang: "हरी मिर्च", slug: "haree mirch" },
  },
  {
    eng: "Indian Gooseberry",
    img: "https://images.pexels.com/photos/14627739/pexels-photo-14627739.jpeg",
    japanese: { lang: "インドのグーズベリー", slug: "Indo no gūzuberī" },
    hindi: { lang: "भारतीय करौदा", slug: "bhaarateey karauda" },
  },
  {
    eng: "Natal Plum",
    img: "https://specialtyproduce.com/sppics/9225.png",
    japanese: { lang: "ナタールプラム", slug: "Natārupuramu" },
    hindi: { lang: "नटली प्लम", slug: "natalee plam" },
  },
  {
    eng: "Colocasia",
    img: "https://www.ohiotropics.com/wp-content/uploads/2022/05/colocasia-esculenta-2-1080x810.jpg",
    japanese: { lang: "コロカシア", slug: "Korokashia" },
    hindi: { lang: "आलुकी", slug: "aalukee" },
  },
  {
    eng: "Amaranth",
    img: "https://images.pexels.com/photos/14448235/pexels-photo-14448235.jpeg",
    japanese: { lang: "アマランス", slug: "Amaransu" },
    hindi: {
      lang: "अम्लान रंगीन पुष्प का पौध",
      slug: "amlaan rangeen pushp ka paudh",
    },
  },
  {
    eng: "Kidney Beans",
    img: "https://images.pexels.com/photos/6316672/pexels-photo-6316672.jpeg",
    japanese: { lang: "インゲン豆", slug: "Ingen mame" },
    hindi: { lang: "राजमा", slug: "raajama" },
  },
  {
    eng: "Eggplant",
    img: "https://1.bp.blogspot.com/-twpj0AZMsWo/VLJFTATb9tI/AAAAAAAAKpo/PuPhR0NfeP8/s1600/eggplant.jpg",
    japanese: { lang: "ナス", slug: "nasu" },
    hindi: { lang: "बैंगन", slug: "baingan" },
  },
  {
    eng: "Peppermint",
    img: "https://images.pexels.com/photos/531260/pexels-photo-531260.jpeg",
    japanese: { lang: "ペパーミント", slug: "Pepāminto" },
    hindi: { lang: "पुदीना", slug: "pudeena" },
  },
  {
    eng: "Raw Papaya",
    img: "https://www.lifeberrys.com/img/article/raw-papaya-1-1508739422-lb.jpg",
    japanese: { lang: "生のパパイヤ", slug: "Nama no papaiya" },
    hindi: { lang: "कच्चा पपीता", slug: "kachcha papeeta" },
  },
  {
    eng: "Basil",
    img: "https://images.pexels.com/photos/1087902/pexels-photo-1087902.jpeg",
    japanese: { lang: "バジル", slug: "Bajiru" },
    hindi: { lang: "तुलसी", slug: "tulasee" },
  },
  {
    eng: "Wasabi",
    img: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2014/05/15/16/p40-wasabi.jpg",
    japanese: { lang: "わさび", slug: "Wasabi" },
    hindi: { lang: "वसाबी", slug: "vasaabee" },
  },
  {
    eng: "Sorrel",
    img: "https://specialtyproduce.com/sppics/11540.png",
    japanese: { lang: "栗色", slug: "Kuriiro" },
    hindi: { lang: "सोरेल", slug: "sorel" },
  },
  {
    eng: "Fava Beans",
    img: "https://www.yabibo.com/wp-content/uploads/2015/05/fava-beans.jpg",
    japanese: { lang: "ソラマメ", slug: "Soramame" },
    hindi: { lang: "फभा सेम", slug: "phabha sem" },
  },
  {
    eng: "Cowpea",
    img: "https://cdn.shopify.com/s/files/1/1698/1675/products/Bean_California_Blackeye_Cowpea.jpg?v=1536780374",
    japanese: { lang: "ササギ", slug: "Sasagi" },
    hindi: { lang: "लोबिया", slug: "lobiya" },
  },
  {
    eng: "Purslane",
    img: "http://1.bp.blogspot.com/-E3-zbu7wjek/U9AmQ0GJO1I/AAAAAAAAETY/yNlzA2DjVfs/s1600/purslane.jpg",
    japanese: { lang: "スクレーン", slug: "Sukurēn" },
    hindi: { lang: "कुलफा का शाक", slug: "kulapha ka shaak" },
  },
  {
    eng: "Shallot",
    img: "https://www.lovethegarden.com/sites/default/files/content/articles/UK_freshly-harvested-shallots.jpg",
    japanese: { lang: "エシャロット", slug: "Esharotto" },
    hindi: { lang: "छोटे प्याज़", slug: "chhote pyaaz" },
  },
  {
    eng: "Broad Beans",
    img: "https://www.asiaseeds.com/wp-content/uploads/2015/01/broad-bean1.jpg",
    japanese: { lang: "そら豆", slug: "Soramame" },
    hindi: { lang: "व्यापक सेम", slug: "vyaapak sem" },
  },
  {
    eng: "Cluster Beans",
    img: "https://img.etsystatic.com/il/d683e5/733414865/il_fullxfull.733414865_29pp.jpg",
    japanese: { lang: "クラスタービーン", slug: "Kurasutābīn" },
    hindi: { lang: "क्लस्टर बीन", slug: "klastar been" },
  },
  {
    eng: "Spine Gourd",
    img: "https://syncwithnature.in/wp-content/uploads/2020/07/SAVE_20200730_190910.jpg",
    japanese: { lang: "脊椎のひょうたん", slug: "Sekitsui no hyōtan" },
    hindi: { lang: "रीढ़ की हड्डी", slug: "reedh kee haddee" },
  },
  {
    eng: "French Beans",
    img: "https://images.pexels.com/photos/872903/pexels-photo-872903.jpeg",
    japanese: { lang: "フレンチビーンズ", slug: "Furenchibīnzu" },
    hindi: { lang: "फ्रेंच बीन्स", slug: "phrench beens" },
  },
  {
    eng: "Raw Banana",
    img: "https://images.healthshots.com/healthshots/en/uploads/2021/10/09112747/Green-banana.jpg",
    japanese: { lang: "生バナナ", slug: "Nama banana" },
    hindi: { lang: "कच्चा केला", slug: "kachcha kela" },
  },
  {
    eng: "Arrowroot",
    img: "https://www.organicfacts.net/wp-content/uploads/arrowroot-2.jpg",
    japanese: { lang: "クズウコン", slug: "Kuzuukon" },
    hindi: { lang: "अरारोट", slug: "araarot" },
  },
  {
    eng: "Chickpea Greens",
    img: "https://images.pexels.com/photos/1192034/pexels-photo-1192034.jpeg",
    japanese: { lang: "ひよこ豆の緑", slug: "Hiyoko mame no midori" },
    hindi: { lang: "छद्गी ग्रीन्स", slug: "chhadgee greens" },
  },
  {
    eng: "banana flower",
    img: "https://www.mashed.com/img/gallery/what-are-banana-flowers-and-can-you-eat-them/l-intro-1622647799.jpg",
    japanese: { lang: "バナナの花", slug: "Banana no ha" },
    hindi: { lang: "केले का फूल", slug: "kele ka phool" },
  },
  {
    eng: "Water Spinach",
    img: "https://specialtyproduce.com/sppics/3132.png",
    japanese: { lang: "ほうれん草", slug: "Hōrensō" },
    hindi: { lang: "कलमी साग", slug: "kalmi saag" },
  },
  {
    eng: "Oregano",
    img: "https://ecocosas.com/wp-content/uploads/2018/07/oregano.jpg",
    japanese: { lang: "オレガノ", slug: "Oregano" },
    hindi: { lang: "ओरिगैनो", slug: "origaino" },
  },
  {
    eng: "Swede",
    img: "https://clinkscarefarm.org.uk/wp-content/uploads/2020/03/swede.jpg",
    japanese: { lang: "スウェーデン人", slug: "Suu~ēden hito" },
    hindi: { lang: "स्वीडिश जहाज़", slug: "sveedish jahaaz" },
  },
  {
    eng: "Olives",
    img: "https://images.pexels.com/photos/4109910/pexels-photo-4109910.jpeg",
    japanese: { lang: "オリーブ", slug: "Orību" },
    hindi: { lang: "जैतून", slug: "jaitoon" },
  },
];

export default data;
